### PR TITLE
Particle in cell

### PR DESCRIPTION
**Pull request by kkormann**
This branch contains several development of the GEMPIC code: curvilinear version, version with clamped spline boundary conditions, strong Ampere version, implicit time propagators, subcycling propagators, implementations in higher dimensions.

### CODE REVIEW

**Comment by kkormann** [comment]
@pnavaro I am trying to understand the reason for the conflict. It might be an issue with the indentation. Do you have a script to clean up the code that we could apply on the `maxwell` branch?

**Comment by pnavaro** [comment]
link to #19

**Comment by pnavaro** [comment]
It is a mistake on cmake config. The parallel make does not work. I will fix this. I reopen this PR and remove the other. Sorry for the mess  :-)

**Comment by kkormann** [comment]
Now I am confused about the two branches. Should I use the `maxwell` or `maxwell_pretify` ?

**Comment by kkormann** [comment]
I just fixed a bug on the other version...

**Comment by pnavaro** [comment]
> I just fixed a bug on the other version...

Ah OK so I reopen the other PR. We will see if tests pass

**Comment by kkormann** [comment]
I guess we can close this merge request, since the #19 one is the more up-to-date now, right?

**Comment by pnavaro** [comment]
I fixed the random values in splines_pp tests but you removed them. There some reasons to do it but we heed something to prevent failed test.

**Comment by kkormann** [comment]
Sorry, I did not remove this intentionally. In the other branch I tried to bring the seed back in but apparently the test still fails...

**Pull request closed without merging**
