### PR TITLE
CMake: omit DESTINATION to install into standard destination

### PR DESCRIPTION
**Pull request by freifrauvonbleifrei**
for installation of `sll_m_sim_bsl_vp_3d3v_cart_dd_slim_interface`.

This is an addendum to https://github.com/selalib/selalib/pull/24 -- I saw that DisCoTec's CMake could not find the interface library without this change. 

Maybe there is a smarter way of doing this?
@pnavaro I think you already realized my CMake skills are not great -- it's true! but I'm trying! ;)

### CODE REVIEW

**Review by pnavaro — APPROVED** [review]
OK I did not test the make install procedure. Sorry.

**Comment by pnavaro** [comment]
CMake configuration that works everywhere is not easy. Thank you !

**Comment by freifrauvonbleifrei** [comment]
thx!

**Comment by freifrauvonbleifrei** [comment]
um @pnavaro I had thought that you merged the branch but it shows only as "closed" -- did you intentionally not merge the change?

**Comment by pnavaro** [comment]
Oups, sorry, I pushed the wrong button...  I fixed it .

**Comment by pnavaro** [comment]
I try to reopen the PR but unfortunately, the original branch was deleted ...

**Comment by pnavaro** [comment]
I invited you to be member of the project. You will be able to make modifications.

**Comment by freifrauvonbleifrei** [comment]
> Oups, sorry, I pushed the wrong button... I fixed it .
> 
> [6eec4c9](https://github.com/selalib/selalib/commit/6eec4c9c5ebe849381fbda838eb925072238d160)

I restored the branch, but cannot see the purple button myself -- is it there for you now? ;)

**Comment by freifrauvonbleifrei** [comment]
thx!

**Pull request merged**
