### PR TITLE
Remove sll_mpi

### PR DESCRIPTION
**Pull request by pnavaro**
Just a try  to see if it works better with spack.

### CODE REVIEW

**Comment by freifrauvonbleifrei** [comment]
@pnavaro consider removing `MPI_Fortran_INCLUDE_PATH` etc before merging, since they will be unset anyways for the newer cmakes.

**Comment by pnavaro** [comment]
> @pnavaro consider removing `MPI_Fortran_INCLUDE_PATH` etc before merging, since they will be unset anyways for the newer cmakes.

Sorry I did not understand

**Comment by pnavaro** [comment]
Dear @kkormann and @paulwilhelmvlasov , could you check if this branch works on your workstation ? There are many changes. @freifrauvonbleifrei made a spack package and it works better by removing the sll_mpi interface. Thanks

**Comment by freifrauvonbleifrei** [comment]
> > @pnavaro consider removing `MPI_Fortran_INCLUDE_PATH` etc before merging, since they will be unset anyways for the newer cmakes.
> 
> Sorry I did not understand

Sorry! I meant that some of the variables that are deprecated from cmake 3.10 onwards (listed at the bottom here: https://cmake.org/cmake/help/latest/module/FindMPI.html ) are used in other places in the code, and I think they should be removed because they are not required -- compiling works for me with cmake 3.27 with all of them unset.

that would be `MPI_Fortran_INCLUDE_PATH`  , `MPI_LIBRARY`, and `MPIEXEC` (which should probably be replaced by `MPIEXEC_EXECUTABLE` for slurm)

**Comment by paulwilhelmvlasov** [comment]
@pnavaro The branch mpi compiles without problems on my workstation and all test ran through and passed.

**Review by paulwilhelmvlasov — APPROVED** [review]

**Pull request merged**
