### PR TITLE
fix finding hdf5 libraries

### PR DESCRIPTION
**Pull request by freifrauvonbleifrei**
When trying to install on HPC systems, I always had these linking problems:

```
[100%] Linking Fortran executable ../../../../bin/test_distribution_function
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5dont_atexit_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:820: undefined reference to `h5dont_atexit_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5garbage_collect_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:791: undefined reference to `h5garbage_collect_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5check_version_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:762: undefined reference to `h5check_version_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5get_libversion_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:724: undefined reference to `h5get_libversion_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5close_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:689: undefined reference to `h5close_types_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/spack/opt/spack/linux-rocky8-zen2/gcc-10.2.0/hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/lib/libhdf5_fortran.a(H5_ff.F90.o): In function `__h5lib_MOD_h5open_f':
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:253: undefined reference to `h5init_types_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:324: undefined reference to `h5init_flags_c'
/lustre/hpe/ws10/ws10.1/ws/ipvpolli-widely-distributed-ct/tmp/ipvpolli/spack-stage/spack-stage-hdf5-1.12.2-zus3dstkj2vej7j57bdydimmjheredpj/spack-src/fortran/src/H5_ff.F90:632: undefined reference to `h5init1_flags_c'
[...]
```

On HAWK, i fixed it by adding the few lines in this PR. They are inspired by https://stackoverflow.com/a/55012310 .
I did not have a chance yet to test on other systems, so this PR is also to see if the tests are still passing.

### CODE REVIEW

**Review by pnavaro — APPROVED** [review]
When I wrote this file, the official CMake module for HDF5 was not exist. It is better to use it now but we probably need to change the minimal required version of CMake

**Comment by pnavaro** [comment]
Ok to change the variable HDF5_INCLUDE_DIR_FORTRAN everywhere but you also need to add 
```cmake
set(HDF5_Fortran_INCLUDE_DIRS  $(HDF5_INCLUDE_DIR_FORTRAN))
```
in the HDF5Config.cmake file when (NOT HDF5_FOUND) . It could happen that find(HDF5) does not work and it will try the old way.

**Comment by pnavaro** [comment]
We have 3.1 now, I checked and we're good 👍 . Thanks Theresa.

**Comment by freifrauvonbleifrei** [comment]
@pnavaro do you think we could bump the cmake version to 3.6? 

Then I could use FindBLAS / FindLAPACK as well: https://www.kitware.com//cmake-3-6-0-rc3-is-now-ready/

**Pull request merged**
